---
# Deploy the vps-git stack to all nodes.
#
# Usage:
#   ansible-playbook deploy.yml                    # deploy to all
#   ansible-playbook deploy.yml -l primary         # primary only
#   ansible-playbook deploy.yml -l standby         # standby only
#   ansible-playbook deploy.yml -l standby -e init_standby_pg=true  # init replica

- name: Deploy vps-git
  hosts: all
  roles:
    - common
    - vps-git
